# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-08-07 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manytoappapplication', '0002_auto_20190807_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='student',
            field=models.ForeignKey(null=True, on_delete=models.SET(3), to='manytoappapplication.Student'),
        ),
    ]
