# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-08-05 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otoapplication', '0003_auto_20190805_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='abc',
            field=models.OneToOneField(null=True, on_delete=models.SET(5), to='otoapplication.Student'),
        ),
    ]
